// src/models/Project.js
//
// Mongoose schema for ArchMind AI projects (imported via GitHub or ZIP upload).
//
// Multi-tenant isolation: Every project is strictly keyed to userId (Clerk User ID).
// A compound index on (userId, github.fullName) prevents duplicate records
// while allowing upserts to refresh repository metadata.

import mongoose from "mongoose";

const treeNodeSchema = new mongoose.Schema(
  {
    path: { type: String, required: true },
    type: { type: String, enum: ["file", "dir"], required: true },
    size: { type: Number, default: 0 },
    sha: { type: String },
  },
  { _id: false }
);

const projectSchema = new mongoose.Schema(
  {
    // Clerk User ID — strict multi-tenant tenant isolation
    userId: {
      type: String,
      required: [true, "User ID is required"],
      index: true,
    },

    // Display name (defaults to repository name or archive name)
    name: {
      type: String,
      required: [true, "Project name is required"],
      trim: true,
    },

    // Ingestion source
    source: {
      type: String,
      enum: ["github", "zip"],
      required: true,
      default: "github",
    },

    // Processing status
    // 'uploaded'   — file received / import recorded, not yet scanned
    // 'processing' — RIE scan + LLM analysis in progress
    // 'completed'  — all analysis artifacts ready
    // 'failed'     — pipeline error; see errorDetails
    status: {
      type: String,
      enum: ["uploaded", "processing", "completed", "failed"],
      default: "uploaded",
      index: true,
    },

    // GitHub-specific metadata (populated when source === 'github')
    github: {
      githubId: { type: Number },
      owner: { type: String, trim: true },
      repo: { type: String, trim: true },
      fullName: { type: String, trim: true }, // e.g. "facebook/react"
      url: { type: String, trim: true },
      ownerAvatar: { type: String, default: "" },
      defaultBranch: { type: String, default: "main" },
      stars: { type: Number, default: 0 },
      forks: { type: Number, default: 0 },
      openIssues: { type: Number, default: 0 },
      language: { type: String, default: "Unknown" },
      topics: { type: [String], default: [] },
      isPrivate: { type: Boolean, default: false },
      isFork: { type: Boolean, default: false },
      size: { type: Number, default: 0 },
      license: { type: String, default: null },
    },

    // ZIP-specific metadata (populated when source === 'zip')
    zip: {
      originalName: { type: String, trim: true },
      sizeBytes: { type: Number, default: 0 },
    },

    // Sanitized file tree (noise filtered by RIE)
    tree: [treeNodeSchema],

    // Summary statistics compiled during scanning
    stats: {
      totalFiles: { type: Number, default: 0 },
      totalDirs: { type: Number, default: 0 },
      totalBytes: { type: Number, default: 0 },
      isTruncated: { type: Boolean, default: false },
      topExtensions: [
        {
          extension: { type: String },
          count: { type: Number },
          _id: false,
        },
      ],
    },

    // Technology stack detected by the RIE scanner
    techStack: {
      languages:  { type: [String], default: [] },
      frameworks: { type: [String], default: [] },
      databases:  { type: [String], default: [] },
      devops:     { type: [String], default: [] },
    },

    // Language identification metadata (Feature 08)
    primaryLanguage: { type: String, default: null },
    secondaryLanguages: { type: [String], default: [] },
    languageDetectionConfidence: { type: Number, default: 0 },

    // System topology graph generated by RIE (React Flow shape)
    topology: {
      nodes: { type: Array, default: [] },
      edges: { type: Array, default: [] },
      generatedAt: { type: Date, default: null },
    },

    // Smart Relevance & Capability Matrix
    capabilities: {
      hasDatabase: { type: Boolean, default: false },
      hasApis: { type: Boolean, default: false },
      hasDevops: { type: Boolean, default: false },
      hasSecuritySensitiveCode: { type: Boolean, default: false },
      details: {
        databases: { type: [String], default: [] },
        frameworks: { type: [String], default: [] },
        devops: { type: [String], default: [] },
      },
    },

    // Tree-sitter AST Structural Intelligence (Feature 12)
    ast: {
      summary: {
        totalFilesParsed: { type: Number, default: 0 },
        totalFilesSkipped: { type: Number, default: 0 },
        errorCount: { type: Number, default: 0 },
        languagesParsed: { type: [String], default: [] },
      },
      files: { type: Array, default: [] },
      imports: { type: Array, default: [] },
      exports: { type: Array, default: [] },
      functions: { type: Array, default: [] },
      classes: { type: Array, default: [] },
      routes: { type: Array, default: [] },
      models: { type: Array, default: [] },
      dependencies: {
        internal: { type: Array, default: [] },
        external: { type: Array, default: [] },
      },
      entryPoints: { type: Array, default: [] },
      errors: { type: Array, default: [] },
    },

    // Repository Blueprint Payload for downstream LLM analysis (Feature 13)
    blueprint: {
      version: { type: Number, default: 1 },
      generatedAt: { type: Date, default: null },
      metadata: { type: Object, default: {} },
      capabilities: { type: Object, default: {} },
      entryPoints: { type: Array, default: [] },
      structure: { type: Array, default: [] },
      dependencies: {
        internal: { type: Array, default: [] },
        external: { type: Array, default: [] },
      },
      routes: { type: Array, default: [] },
      models: { type: Array, default: [] },
      classes: { type: Array, default: [] },
      functions: { type: Array, default: [] },
      tokenEstimate: { type: Number, default: 0 },
      isBudgetTruncated: { type: Boolean, default: false },
    },

    // Temporary extraction path used during RIE processing.
    // Populated during in-flight extraction; cleared (set to null) after cleanup.
    // Stored so that a crashed job can resume or be inspected.
    extractionPath: {
      type: String,
      default: null,
    },

    // Error details captured when status === 'failed'
    errorDetails: {
      message: { type: String, default: null },
      code:    { type: String, default: null },
      at:      { type: Date,   default: null },
    },

    // Per-module analysis status tracking
    // Each module follows: idle → queued → processing → completed → failed
    analysis: {
      architecture: {
        status: { type: String, enum: ["idle", "queued", "processing", "completed", "failed"], default: "idle" },
        analysisId: { type: String, default: null },
        completedAt: { type: Date, default: null },
        errorMessage: { type: String, default: null },
      },
      erd: {
        status: { type: String, enum: ["idle", "queued", "processing", "completed", "failed"], default: "idle" },
        analysisId: { type: String, default: null },
        completedAt: { type: Date, default: null },
        errorMessage: { type: String, default: null },
      },
      api: {
        status: { type: String, enum: ["idle", "queued", "processing", "completed", "failed"], default: "idle" },
        analysisId: { type: String, default: null },
        completedAt: { type: Date, default: null },
        errorMessage: { type: String, default: null },
      },
      security: {
        status: { type: String, enum: ["idle", "queued", "processing", "completed", "failed"], default: "idle" },
        analysisId: { type: String, default: null },
        completedAt: { type: Date, default: null },
        errorMessage: { type: String, default: null },
      },
      devops: {
        status: { type: String, enum: ["idle", "queued", "processing", "completed", "failed"], default: "idle" },
        analysisId: { type: String, default: null },
        completedAt: { type: Date, default: null },
        errorMessage: { type: String, default: null },
      },
    },

    // Cached analysis results/artifacts generated by downstream AI modules
    analysisResults: {
      type: mongoose.Schema.Types.Mixed,
      default: null,
    },
  },
  {
    timestamps: true,
    versionKey: false,
  }
);

// Compound index: prevent duplicate GitHub repo records per user
projectSchema.index(
  { userId: 1, "github.fullName": 1 },
  {
    unique: true,
    partialFilterExpression: { source: "github", "github.fullName": { $exists: true } },
  }
);

// Compound index: prevent duplicate ZIP uploads with the same name per user
projectSchema.index(
  { userId: 1, "zip.originalName": 1 },
  {
    unique: true,
    partialFilterExpression: { source: "zip", "zip.originalName": { $exists: true } },
  }
);

// Sanitized response shape returned to clients
projectSchema.methods.toSafeObject = function () {
  const defaultModuleStatus = { status: "idle", analysisId: null, completedAt: null, errorMessage: null };
  const analysis = this.analysis || {};
  return {
    id: this._id,
    userId: this.userId,
    name: this.name,
    source: this.source,
    status: this.status,
    github: this.github,
    zip: this.zip,
    stats: this.stats,
    techStack: this.techStack,
    primaryLanguage: this.primaryLanguage,
    secondaryLanguages: this.secondaryLanguages,
    languageDetectionConfidence: this.languageDetectionConfidence,
    topology: this.topology,
    capabilities: this.capabilities,
    ast: this.ast || null,
    blueprint: this.blueprint || null,
    analysisResults: this.analysisResults || null,
    analysis: {
      architecture: analysis.architecture || defaultModuleStatus,
      erd: analysis.erd || defaultModuleStatus,
      api: analysis.api || defaultModuleStatus,
      security: analysis.security || defaultModuleStatus,
      devops: analysis.devops || defaultModuleStatus,
    },
    errorDetails: this.errorDetails?.message ? this.errorDetails : null,
    treeCount: this.tree?.length || 0,
    createdAt: this.createdAt,
    updatedAt: this.updatedAt,
  };
};

const Project = mongoose.model("Project", projectSchema);

export default Project;
