import React, { useState, useRef } from "react";
import { motion, AnimatePresence } from "framer-motion";

const codeSnippets = {
  "k8s-deployment.yaml": `# Generated by ArchMind AI engine
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        version: v2.4.0
    spec:
      containers:
      - name: gateway
        image: archmind/gateway:v2.4
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: NODE_ENV
          value: "production"`,
  Dockerfile: `# Multi-stage container synthesis
FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production
COPY . .
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=builder /app/dist ./dist
EXPOSE 8080
USER node
CMD ["node", "dist/main.js"]`,
  "pipeline.yml": `name: ArchMind Automated CI/CD
on:
  push:
    branches: [ main ]

jobs:
  synthesize-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run AST Graph Validation
      run: npx archmind-engine --strict
    - name: Build & Push Container
      run: |
        docker build -t app:v2.4 .
        kubectl apply -f k8s/`,
};

export default function HeroSection({ onAnalyze }) {
  const [repoUrl, setRepoUrl] = useState("");
  const [activeCodeTab, setActiveCodeTab] = useState("k8s-deployment.yaml");
  const [copied, setCopied] = useState(false);
  const [activeNode, setActiveNode] = useState(null);
  const [zoomLevel, setZoomLevel] = useState(100);

  const containerRef = useRef(null);
  const [mousePos, setMousePos] = useState({ x: 0, y: 0 });

  const handleMouseMove = (e) => {
    if (!containerRef.current) return;
    const rect = containerRef.current.getBoundingClientRect();
    setMousePos({
      x: e.clientX - rect.left,
      y: e.clientY - rect.top,
    });
  };

  const sampleRepos = [
    { label: "fastapi/fastapi", url: "https://github.com/fastapi/fastapi" },
    { label: "supabase/postgres", url: "https://github.com/supabase/postgres" },
  ];

  const handleCopyCode = () => {
    navigator.clipboard.writeText(codeSnippets[activeCodeTab]);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleAnalyzeSubmit = (e) => {
    e.preventDefault();
    if (onAnalyze && repoUrl) onAnalyze(repoUrl);
  };

  return (
    <section
      ref={containerRef}
      onMouseMove={handleMouseMove}
      className="relative min-h-screen pt-28 sm:pt-32 pb-20 px-4 sm:px-6 lg:px-8 flex flex-col items-center justify-center overflow-hidden"
    >
      {/* 1. Dynamic Cursor Spotlight & Ambient Blueprint Lighting */}
      <div
        className="pointer-events-none absolute inset-0 opacity-40 transition-opacity duration-300 -z-10"
        style={{
          background: `radial-gradient(650px circle at ${mousePos.x}px ${mousePos.y}px, rgba(6, 182, 212, 0.12), rgba(99, 102, 241, 0.05), transparent 75%)`,
        }}
      />

      {/* Global Ambient Glow Halos */}
      <div className="absolute top-1/4 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[700px] sm:w-[1000px] h-[450px] bg-gradient-to-tr from-cyan-600/20 via-indigo-600/15 to-transparent blur-[140px] pointer-events-none -z-10" />

      {/* Technical Grid Pattern Overlay */}
      <div className="absolute inset-0 opacity-[0.035] pointer-events-none -z-10 bg-[radial-gradient(#38bdf8_1px,transparent_1px)] [background-size:28px_28px]" />

      {/* 2. Top Header Status Pill */}
      <motion.div
        initial={{ opacity: 0, y: -20, scale: 0.95 }}
        animate={{ opacity: 1, y: 0, scale: 1 }}
        transition={{ duration: 0.5, ease: [0.16, 1, 0.3, 1] }}
        className="group relative inline-flex items-center gap-2.5 px-3.5 py-1.5 rounded-full bg-[#0a1020]/90 border border-cyan-500/30 shadow-[0_0_20px_rgba(6,182,212,0.15)] mb-7 select-none backdrop-blur-md"
      >
        <span className="relative flex h-2 w-2">
          <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-cyan-400 opacity-75" />
          <span className="relative inline-flex rounded-full h-2 w-2 bg-cyan-400 shadow-[0_0_8px_rgba(6,182,212,0.8)]" />
        </span>
        <span className="text-[11px] sm:text-xs font-mono font-bold tracking-widest text-cyan-300 uppercase">
          AST PARSER v2.4 ONLINE
        </span>
        <span className="text-slate-600">|</span>
        <span className="text-[10px] font-mono text-slate-400">
          4.2M TOKENS/SEC
        </span>
      </motion.div>

      {/* 3. Main Headline & Subheading */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, delay: 0.1, ease: [0.16, 1, 0.3, 1] }}
        className="text-center max-w-4xl mx-auto space-y-4 mb-9"
      >
        <h1 className="text-4xl sm:text-6xl lg:text-7xl font-black tracking-tight text-white leading-[1.08]">
          Code in. <br />
          <span className="text-transparent bg-clip-text bg-gradient-to-b from-white via-slate-100 to-slate-400">
            Living Architecture{" "}
          </span>
          <span className="relative inline-block text-cyan-400 font-mono">
            [Synthesized]
            <motion.span
              className="absolute -bottom-1 left-0 right-0 h-[2px] bg-gradient-to-r from-cyan-400 to-blue-500 rounded-full shadow-[0_0_8px_rgba(6,182,212,0.6)]"
              initial={{ width: 0 }}
              animate={{ width: "100%" }}
              transition={{ delay: 0.6, duration: 0.8 }}
            />
          </span>
          .
        </h1>
        <p className="text-sm sm:text-base text-slate-400 max-w-2xl mx-auto leading-relaxed">
          Stop parsing thousands of files manually. ArchMind synthesizes
          dependency call graphs, database ERDs, and production DevOps manifests
          directly from your AST.
        </p>
      </motion.div>

      {/* 4. Command Ingest Palette Bar */}
      <motion.div
        initial={{ opacity: 0, scale: 0.96 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ duration: 0.5, delay: 0.2 }}
        className="w-full max-w-xl mb-3"
      >
        <form
          onSubmit={handleAnalyzeSubmit}
          className="relative flex items-center bg-[#090e1b]/95 backdrop-blur-xl border border-white/15 focus-within:border-cyan-500/60 focus-within:shadow-[0_0_25px_rgba(6,182,212,0.25)] rounded-2xl p-1.5 shadow-[0_12px_40px_rgba(0,0,0,0.6)] transition-all duration-300"
        >
          <div className="pl-3.5 pr-2 text-slate-400 flex items-center select-none font-mono text-sm">
            <span className="text-cyan-400 font-bold mr-1.5">&gt;_</span>
          </div>

          <input
            type="text"
            value={repoUrl}
            onChange={(e) => setRepoUrl(e.target.value)}
            placeholder="git clone https://github.com/..."
            className="w-full bg-transparent text-xs sm:text-sm text-slate-100 placeholder-slate-500 focus:outline-none font-mono py-2"
          />

          <motion.button
            whileHover={{ scale: 1.02 }}
            whileTap={{ scale: 0.96 }}
            type="submit"
            className="relative flex items-center justify-center px-5 sm:px-6 py-2.5 rounded-xl bg-gradient-to-r from-blue-600 via-cyan-500 to-indigo-600 hover:from-blue-500 hover:to-cyan-400 text-white text-xs font-mono font-bold tracking-wider uppercase transition-all duration-200 shadow-[0_0_20px_rgba(6,182,212,0.35)] shrink-0 overflow-hidden"
          >
            <span className="relative z-10">ANALYZE</span>
            <div className="absolute inset-0 -translate-x-full hover:translate-x-full bg-gradient-to-r from-transparent via-white/20 to-transparent transition-transform duration-700 pointer-events-none" />
          </motion.button>
        </form>

        {/* Quick Sample Repository Chips */}
        <div className="flex flex-wrap items-center justify-center gap-2 mt-3.5 text-xs text-slate-400 font-mono">
          {sampleRepos.map((sample) => (
            <button
              key={sample.label}
              type="button"
              onClick={() => setRepoUrl(sample.url)}
              className="inline-flex items-center gap-1.5 px-3 py-1 rounded-lg bg-[#0c1324]/80 border border-white/10 hover:border-cyan-500/40 hover:text-cyan-300 hover:bg-cyan-500/[0.04] transition-all"
            >
              <span className="text-cyan-400">⚡</span>
              <span>Try: {sample.label}</span>
            </button>
          ))}
          <button
            type="button"
            className="inline-flex items-center gap-1.5 px-3 py-1 rounded-lg bg-[#0c1324]/80 border border-white/10 hover:border-amber-500/40 hover:text-amber-300 hover:bg-amber-500/[0.04] transition-all"
          >
            <span>📁</span>
            <span>Drop .zip / repo</span>
          </button>
        </div>
      </motion.div>

      {/* 5. Main Split-Pane Interactive IDE Window */}
      <motion.div
        initial={{ opacity: 0, y: 40 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.7, delay: 0.3, ease: [0.16, 1, 0.3, 1] }}
        className="w-full max-w-5xl mt-6 rounded-2xl bg-[#080d1a]/95 border border-white/15 shadow-[0_25px_70px_rgba(0,0,0,0.85),0_0_35px_rgba(6,182,212,0.12)] overflow-hidden backdrop-blur-xl"
      >
        {/* IDE Titlebar */}
        <div className="px-4 py-2.5 bg-[#050914] border-b border-white/10 flex items-center justify-between select-none">
          <div className="flex items-center gap-2">
            <span className="w-3 h-3 rounded-full bg-[#ff5f56]/90 border border-[#e0443e]" />
            <span className="w-3 h-3 rounded-full bg-[#ffbd2e]/90 border border-[#dea123]" />
            <span className="w-3 h-3 rounded-full bg-[#27c93f]/90 border border-[#1aab29]" />
          </div>

          <div className="inline-flex items-center gap-2 px-3 py-0.5 rounded-md bg-[#0a1020] border border-cyan-500/20 text-[11px] font-mono text-cyan-300 shadow-inner">
            <svg
              className="w-3.5 h-3.5 text-cyan-400"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
            >
              <path d="M4 6h16M4 12h16m-7 6h7" />
            </svg>
            <span>Topology View</span>
          </div>

          <div className="flex items-center gap-2 text-xs font-mono text-slate-500">
            <span className="hidden sm:inline">branch:</span>
            <span className="text-cyan-400/80">main*</span>
          </div>
        </div>

        {/* Split Grid: Topology Visualizer + Code Terminal */}
        <div className="grid grid-cols-1 lg:grid-cols-12 min-h-[480px]">
          {/* LEFT PANE: Interactive Topology Graph (7 Cols) */}
          <div className="lg:col-span-7 p-5 bg-[#070b16] relative flex flex-col justify-between overflow-hidden border-b lg:border-b-0 lg:border-r border-white/10">
            {/* Top Canvas Controls */}
            <div className="flex items-center justify-between mb-4 z-10">
              <div className="flex items-center gap-2">
                <span className="w-2 h-2 rounded-full bg-cyan-400 animate-ping" />
                <span className="text-[11px] font-mono font-bold uppercase tracking-wider text-slate-300">
                  LIVE AST GRAPH
                </span>
              </div>

              <div className="flex items-center gap-1 px-2 py-0.5 rounded-lg bg-[#0b1222] border border-white/10 text-xs font-mono text-slate-400">
                <button
                  type="button"
                  onClick={() =>
                    setZoomLevel((prev) => Math.max(prev - 10, 50))
                  }
                  className="hover:text-white px-1.5 transition-colors"
                >
                  -
                </button>
                <span className="text-slate-200">{zoomLevel}%</span>
                <button
                  type="button"
                  onClick={() =>
                    setZoomLevel((prev) => Math.min(prev + 10, 150))
                  }
                  className="hover:text-white px-1.5 transition-colors"
                >
                  +
                </button>
              </div>
            </div>

            {/* SVG Connecting Vector Curves & Kinetic Data Packets */}
            <div className="relative w-full h-[330px] my-auto">
              <svg className="absolute inset-0 w-full h-full pointer-events-none z-0">
                <defs>
                  <linearGradient
                    id="cyanLine"
                    x1="0%"
                    y1="0%"
                    x2="100%"
                    y2="100%"
                  >
                    <stop offset="0%" stopColor="#06b6d4" stopOpacity="0.8" />
                    <stop offset="100%" stopColor="#3b82f6" stopOpacity="0.3" />
                  </linearGradient>
                </defs>

                {/* Gateway -> Core API */}
                <path
                  d="M 180 45 C 200 90, 220 110, 250 140"
                  fill="none"
                  stroke="url(#cyanLine)"
                  strokeWidth="1.5"
                  strokeDasharray="4 3"
                />

                {/* Gateway -> Auth Service */}
                <path
                  d="M 130 70 C 100 100, 80 120, 65 150"
                  fill="none"
                  stroke="#06b6d4"
                  strokeWidth="1.5"
                  strokeOpacity="0.4"
                />

                {/* Core API -> PostgreSQL */}
                <path
                  d="M 290 185 C 310 210, 320 220, 340 240"
                  fill="none"
                  stroke="#3b82f6"
                  strokeWidth="1.5"
                  strokeDasharray="4 3"
                />

                {/* Core API -> Redis */}
                <path
                  d="M 245 190 C 205 210, 175 220, 145 240"
                  fill="none"
                  stroke="#06b6d4"
                  strokeWidth="1.5"
                  strokeOpacity="0.4"
                />

                {/* Dynamic Data Flow Pulse Dots */}
                <circle
                  cx="215"
                  cy="92"
                  r="3"
                  fill="#38bdf8"
                  className="animate-pulse shadow-[0_0_8px_#38bdf8]"
                />
                <circle
                  cx="315"
                  cy="212"
                  r="3"
                  fill="#818cf8"
                  className="animate-pulse shadow-[0_0_8px_#818cf8]"
                />
              </svg>

              {/* Node 1: API Gateway */}
              <motion.div
                whileHover={{ scale: 1.04 }}
                onMouseEnter={() => setActiveNode("gateway")}
                onMouseLeave={() => setActiveNode(null)}
                className={`absolute top-2 left-[25%] -translate-x-1/2 z-10 w-44 rounded-xl p-2.5 transition-all duration-200 cursor-pointer ${
                  activeNode === "gateway"
                    ? "bg-[#0f1b33] border-cyan-400 shadow-[0_0_25px_rgba(6,182,212,0.4)]"
                    : "bg-[#0b1222]/90 border-cyan-500/40 shadow-[0_0_15px_rgba(6,182,212,0.15)]"
                } border`}
              >
                <div className="flex items-center justify-between text-[11px] font-bold text-white mb-1">
                  <div className="flex items-center gap-1.5">
                    <span className="text-cyan-400 text-xs">❖</span>
                    <span>API Gateway</span>
                  </div>
                  <span className="text-[9px] font-mono text-cyan-400 bg-cyan-950/60 px-1.5 py-0.2 rounded border border-cyan-500/20">
                    ● 99.9%
                  </span>
                </div>
                <div className="flex items-center justify-between text-[10px] font-mono text-slate-400">
                  <span>Kong / Go</span>
                  <span className="text-cyan-300">:80</span>
                </div>
              </motion.div>

              {/* Protocol Badge */}
              <div className="absolute top-[34%] left-[19%] -translate-x-1/2 z-10 px-2 py-0.5 rounded bg-[#060a14] border border-cyan-500/30 text-[9px] font-mono text-cyan-300 shadow">
                HTTP / REST
              </div>

              {/* Node 2: Auth Service */}
              <motion.div
                whileHover={{ scale: 1.04 }}
                onMouseEnter={() => setActiveNode("auth")}
                onMouseLeave={() => setActiveNode(null)}
                className={`absolute top-[48%] left-[2%] z-10 w-36 rounded-xl p-2 transition-all duration-200 cursor-pointer ${
                  activeNode === "auth"
                    ? "bg-[#0f1b33] border-cyan-400 shadow-[0_0_20px_rgba(6,182,212,0.3)]"
                    : "bg-[#090e1b]/90 border-white/15 shadow-lg"
                } border`}
              >
                <div className="flex items-center gap-1.5 text-[11px] font-semibold text-slate-200 mb-1">
                  <span className="text-slate-400">🛡️</span>
                  <span>Auth Service</span>
                </div>
                <div className="flex items-center justify-between text-[10px] font-mono text-slate-400">
                  <span>FastAPI</span>
                  <span className="text-slate-300">:8000</span>
                </div>
              </motion.div>

              {/* Node 3: Core API */}
              <motion.div
                whileHover={{ scale: 1.04 }}
                onMouseEnter={() => setActiveNode("core")}
                onMouseLeave={() => setActiveNode(null)}
                className={`absolute top-[42%] right-[20%] z-10 w-44 rounded-xl p-2.5 transition-all duration-200 cursor-pointer ${
                  activeNode === "core"
                    ? "bg-[#0f1b33] border-cyan-400 shadow-[0_0_25px_rgba(6,182,212,0.4)]"
                    : "bg-[#0b1426]/95 border-cyan-500/50 shadow-[0_0_20px_rgba(6,182,212,0.2)]"
                } border`}
              >
                <div className="flex items-center justify-between text-[11px] font-bold text-white mb-1">
                  <div className="flex items-center gap-1.5">
                    <span className="text-cyan-400">⚙️</span>
                    <span>Core API</span>
                  </div>
                  <span className="text-[9px] font-mono text-cyan-400 bg-cyan-950/60 px-1.5 py-0.2 rounded border border-cyan-500/20">
                    ● 99.9%
                  </span>
                </div>
                <div className="flex items-center justify-between text-[10px] font-mono text-slate-400">
                  <span>Node.js</span>
                  <span className="text-cyan-300">:8080</span>
                </div>
              </motion.div>

              {/* Node 4: Redis Cache */}
              <motion.div
                whileHover={{ scale: 1.04 }}
                onMouseEnter={() => setActiveNode("redis")}
                onMouseLeave={() => setActiveNode(null)}
                className={`absolute bottom-1 left-[14%] z-10 w-36 rounded-xl p-2 transition-all duration-200 cursor-pointer ${
                  activeNode === "redis"
                    ? "bg-[#0f1b33] border-red-400 shadow-[0_0_20px_rgba(239,68,68,0.3)]"
                    : "bg-[#090e1b]/90 border-white/15 shadow-lg"
                } border`}
              >
                <div className="flex items-center gap-1.5 text-[11px] font-semibold text-slate-200 mb-1">
                  <span className="text-red-400">⚡</span>
                  <span>Redis Cache</span>
                </div>
                <div className="flex items-center justify-between text-[10px] font-mono text-slate-400">
                  <span>Cluster</span>
                  <span className="text-slate-300">:6379</span>
                </div>
              </motion.div>

              {/* Node 5: PostgreSQL */}
              <motion.div
                whileHover={{ scale: 1.04 }}
                onMouseEnter={() => setActiveNode("postgres")}
                onMouseLeave={() => setActiveNode(null)}
                className={`absolute bottom-1 right-[8%] z-10 w-44 rounded-xl p-2 transition-all duration-200 cursor-pointer ${
                  activeNode === "postgres"
                    ? "bg-[#0f1b33] border-blue-400 shadow-[0_0_20px_rgba(59,130,246,0.3)]"
                    : "bg-[#090e1b]/90 border-blue-500/40 shadow-lg"
                } border`}
              >
                <div className="flex items-center justify-between text-[11px] font-semibold text-slate-200 mb-1">
                  <div className="flex items-center gap-1.5">
                    <span className="text-blue-400">🗄️</span>
                    <span>PostgreSQL</span>
                  </div>
                  <span className="text-[9px] font-mono text-amber-400 bg-amber-950/60 px-1.5 py-0.2 rounded border border-amber-500/20">
                    ● Syncing
                  </span>
                </div>
                <div className="flex items-center justify-between text-[10px] font-mono text-slate-400">
                  <span>Primary DB</span>
                  <span className="text-blue-300">:5432</span>
                </div>
              </motion.div>

              {/* Radar Minimap */}
              <div className="hidden sm:block absolute bottom-2 right-2 w-16 h-12 rounded-lg bg-[#050811]/90 border border-white/10 p-1 pointer-events-none z-10">
                <div className="w-1.5 h-1.5 rounded-full bg-cyan-400 absolute top-2 left-6 animate-ping" />
                <div className="w-1.5 h-1.5 rounded-full bg-blue-400 absolute bottom-3 right-4" />
                <div className="w-1.5 h-1.5 rounded-full bg-slate-400 absolute bottom-3 left-3" />
              </div>
            </div>

            {/* Bottom Status Banner */}
            <div className="flex items-center justify-between pt-3 border-t border-white/5 text-[10px] font-mono text-slate-500 z-10">
              <span className="flex items-center gap-1.5 text-cyan-400">
                <span className="w-1.5 h-1.5 rounded-full bg-cyan-400 animate-pulse" />
                Auto-sync active
              </span>
              <span>AST Depth: 8 Levels</span>
            </div>
          </div>

          {/* RIGHT PANE: Code / Manifest Terminal View (5 Cols) */}
          <div className="lg:col-span-5 bg-[#050811] flex flex-col justify-between">
            {/* Terminal Tab Bar */}
            <div className="flex items-center justify-between bg-[#04060d] border-b border-white/10 px-3 py-1.5 text-xs font-mono select-none">
              <div className="flex items-center gap-1 overflow-x-auto">
                {Object.keys(codeSnippets).map((tabName) => {
                  const isActive = activeCodeTab === tabName;
                  return (
                    <button
                      key={tabName}
                      type="button"
                      onClick={() => setActiveCodeTab(tabName)}
                      className={`px-2.5 py-1 rounded-md text-[11px] transition-all flex items-center gap-1.5 ${
                        isActive
                          ? "bg-[#0b1222] text-cyan-300 border border-cyan-500/30 shadow-[0_0_10px_rgba(6,182,212,0.15)]"
                          : "text-slate-400 hover:text-slate-200 hover:bg-white/[0.02]"
                      }`}
                    >
                      <span>📄</span>
                      <span className="truncate max-w-[110px]">{tabName}</span>
                    </button>
                  );
                })}
              </div>

              {/* 1-Click Copy Code Button */}
              <button
                type="button"
                onClick={handleCopyCode}
                className="flex items-center gap-1 text-[11px] text-slate-400 hover:text-white px-2 py-1 rounded hover:bg-white/5 transition-colors shrink-0"
                title="Copy code"
              >
                {copied ? (
                  <span className="text-emerald-400">✓ Copied</span>
                ) : (
                  <>
                    <svg
                      className="w-3.5 h-3.5"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="2"
                    >
                      <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
                      <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
                    </svg>
                    <span className="hidden sm:inline">Copy</span>
                  </>
                )}
              </button>
            </div>

            {/* Syntax-Highlighted Code Body */}
            <div className="p-4 font-mono text-xs overflow-x-auto leading-relaxed text-slate-300 max-h-[390px]">
              <pre className="flex">
                {/* Gutter Line Numbers */}
                <span className="select-none text-slate-600 pr-4 text-right">
                  {codeSnippets[activeCodeTab].split("\n").map((_, i) => (
                    <span key={i} className="block">
                      {i + 1}
                    </span>
                  ))}
                </span>

                {/* Formatted Syntax Lines */}
                <code className="text-cyan-200">
                  {codeSnippets[activeCodeTab].split("\n").map((line, idx) => {
                    if (line.startsWith("#")) {
                      return (
                        <span key={idx} className="block text-amber-400/90">
                          {line}
                        </span>
                      );
                    }
                    if (line.includes(":")) {
                      const [key, ...val] = line.split(":");
                      return (
                        <span key={idx} className="block">
                          <span className="text-cyan-400">{key}:</span>
                          <span className="text-emerald-300">
                            {val.join(":")}
                          </span>
                        </span>
                      );
                    }
                    return (
                      <span key={idx} className="block text-slate-300">
                        {line}
                      </span>
                    );
                  })}
                </code>
              </pre>
            </div>

            {/* Bottom Terminal Telemetry Bar */}
            <div className="px-4 py-2 border-t border-white/5 bg-[#03050a] flex items-center justify-between text-[11px] font-mono text-slate-500">
              <span>env: production</span>
              <span className="text-emerald-400">● Validated K8s</span>
            </div>
          </div>
        </div>
      </motion.div>

      {/* 6. Bottom System Telemetry Strip */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.6, duration: 0.5 }}
        className="w-full max-w-5xl mt-5 flex flex-wrap items-center justify-between text-xs font-mono text-slate-500 px-2 select-none"
      >
        <span>©2026 ARCHMIND_AI // SYSTEM_OPERATIONAL</span>
        <div className="flex items-center gap-4">
          <span>
            Latency:{" "}
            <strong className="text-slate-300 font-normal">14ms</strong>
          </span>
          <span>
            Status:{" "}
            <strong className="text-emerald-400 font-normal">Stable</strong>
          </span>
          <span>
            Uptime: <strong className="text-cyan-400 font-normal">99.9%</strong>
          </span>
        </div>
      </motion.div>
    </section>
  );
}
